spring.application.name=flashcards

spring.jpa.hibernate.ddl-auto=update

spring.datasource.url=jdbc:postgresql://dpg-d8b8u4i8qa3s73dllu5g-a.singapore-postgres.render.com/flashcards_8jjo

spring.datasource.username=flashcards_user

spring.datasource.password=bZ7acpDrO03ElDMk2X80mVL5y70qmIcd

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect